### ISSUE TITLE
Slows, Freezes, Dies....

### ISSUE THREAD

**Issue by ArSd-g** [cryptoprofitswitcher/CryptoProfitSwitcher#35]
Since latest 5.5.1 app freeze/stop on profit check coins in the begining of app boot... 
I tried everything new windows 10 1709, 1803, 1809, drivers 18.6.1, huges pages, powershell admin/user, partitions, uefi, owners clear cache ..... everything ....but this fucking code keeps on freezing/stop before SRBMiner allowed to be launch....

FIX THIS PLEASE OR GIVE A SOLUTION OR CLUES!!!!!!!

Screenshot Mining Haven: "SRBMiner keep mining during cryptonightprofitswitcher.exe is having tea....i waited for 30 min...CPS still on the moon! "

![capture d ecran 3](https://user-images.githubusercontent.com/42816950/47403024-43358c00-d748-11e8-9b88-d3b3ef08ab35.png)

**Comment by cryptoprofitswitcher** [comment]
Try the new version V.6.0.0, I may have fixed this in commit https://github.com/cryptoprofitswitcher/CryptonightProfitSwitcher/commit/f5226300727be94d76a6e0d8d0d8c4bb88954db5 

If you still have the problem, then please enable logging and send the log.
